// generated by "sampctl package init"
#include <a_samp>
#include "achinc.inc"

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
}

#define ACHIEVEMENTS_WELCOME (0)

public OnGameModeInit()
{
	Achievements_Create(ACHIEVEMENTS_WELCOME, "Welcome", "Use /welcome command.");

	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/welcome", true))
  {
		Achievements_Unlock(playerid, ACHIEVEMENTS_WELCOME);
    SendClientMessage(playerid, -1, "Achievements_Unlock");
    return 1;
  }

	if(!strcmp(cmdtext, "/achi", true))
  {
		Achievements_ShowDialog(playerid);
    SendClientMessage(playerid, -1, "Achievements_ShowDialog");
    return 1;
  }

	return 0;
}